version: '3.1'
networks:  
  mynetwork:
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on: 
      - ghost
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
      - ./data/certbot/www/letsencrypt:/etc/nginx/snippets/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt/:/var/www/letsencrypt/
    ports:
      - 80:80
      - 443:443
    environment: 
      - GHOST_NAME=${ghost_name}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    depends_on: 
      - db
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    networks:
      - mynetwork
    ports:
      - 2368:2368
    environment:
      url: https://${ghost_name}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${database_user}
      database__connection__password: ${database_password}
      database__connection__database: ${database_name}

  db:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    container_name: db
    networks:
      - mynetwork
    environment:
      MYSQL_DATABASE: ${database_name}
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: ${database_user}
      MYSQL_PASSWORD: ${database_password}
    volumes:
      - ./db:/var/lib/mysql:rw
    ports:
      - 3306:3306
