version: '3.1'
networks:  
  mynetwork:
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on: 
      - ghost
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/www/letsencrypt:/etc/nginx/snippets/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt/:/var/www/letsencrypt/
    ports:
      - 80:80
      - 443:443
  
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    depends_on: 
      - db
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    networks:
      - mynetwork
    ports:
      - 2368:2368
    environment:
      url: https://site.fredericpinaud.ovh
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost

  db:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    container_name: db
    networks:
      - mynetwork
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    ports:
      - 3306:3306
